name: C++ Build and Run

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_run:
    runs-on: windows-2019

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up MSBuild
      run: |
        echo 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin' >> $GITHUB_PATH

    - name: Build project
      run: msbuild /p:Configuration=Release 

    - name: Run executable
      run: .\x64\release\cpp-pass-params.exe
