name: 2019 msbuild

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_run:
    runs-on: windows-2019

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: Ms Build through VS Cmd Prompt
      run: |
        & "c:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\Tools\VsDevCmd.bat"
        $currentDirectory = Get-Location
        Write-Host "Working Directory: $currentDirectory"
        Write-Host "Calling msbuild"
        & "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\msbuild.exe" /p:Configuration=Release
    
    - name: Run executable
      run: | 
        Write-Host "Find and execute"
         $exePath = Get-ChildItem -Path "x64\Release" -Filter "*.exe" -Recurse | Select-Object -First 1 -ExpandProperty FullName
        if ($exePath) {
          Write-Host "Executable found: $exePath"
          & $exePath
        } else {
          Write-Host "No Executable found."
        }
