name: C++ 2019 vs build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_run:
    runs-on: windows-2019

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: Find Visual Studio installation path
      id: find_vs_path
      run: |
        cd "%VSINSTALLDIR%\Common7\Tools"
        .\VsDevCmd.bat
        call VsDevCmd.bat -arch=x86 -host_arch=x64
        echo "Visual Studio environment setup completed."        
    - name: Build project
      run: msbuild /p:Configuration=Release 

    - name: Run executable
      run: .\x64\release\cpp-pass-params.exe
