name: C++ 2019 vs build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_run:
    runs-on: windows-2019

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: Enter VS Cmd terminal through PS
      run: |
        $currentDirectory = Get-Location
        Write-Host "Current directory before entering VS Cmd terminal: $currentDirectory"
        echo "::set-output name=current_directory::$currentDirectory"
        Push-Location
        Set-Location "c:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\Tools\"
        .\VsDevCmd.bat
        $currentDirectory = Get-Location
        Write-Host "Current directory after exiting VS Cmd terminal: $currentDirectory"
        Pop-Location
        $currentDirectory = Get-Location
        Write-Host "Current directory after changing back: $currentDirectory"
        where.exe msbuild
        "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\msbuild.exe"
   
    - name: Run executable
      run: .\x64\release\cpp-pass-params.exe
