name: C++ 2019 vs build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_run:
    runs-on: windows-2019

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: Find Visual Studio installation path
      id: find_vs_path
      run: |
        cd "c:\Program Files\Microsoft Visual Studio"
        dir
        cd "c:\Program Files (x86)\Microsoft Visual Studio"
        dir
        cd '.\Enterprise\Common7\Tools\'
        .\VsDevCmd.bat
        
    - name: Build project
      run: msbuild /p:Configuration=Release 

    - name: Run executable
      run: .\x64\release\cpp-pass-params.exe
