---
name: 2019 msbuild

on:
  push:
    branches: ["main_1"]
  pull_request:
    branches: ["main_1"]

env:
  SLN_PATH: .

  B_CONFIG: Release

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-2019

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1
        with:
          vsVersion: 16.0

      - name: MS Build
        working-directory: ${{env.GITHUB_WORKSPACE}}
        run: |
          msbuild /m /p:Configuration=${{env.B_CONFIG}} ${{env.SLN_PATH}}

      - name: Run Any executable
        run: |
         Write-Host "Find and execute"
         $exePath: >
          Get-ChildItem -Path "x64\Release" -Filter "*.exe" -Recurse |
          Select-Object -First 1 -ExpandProperty FullName
         if ($exePath) {
            Write-Host "Executable found: $exePath"
            & $exePath
         } else {
           Write-Host "No Executable found."
         }
---
