name: C++ 2019 vs build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_run:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Visual Studio Build Tools
      uses: ilammy/msbuild-tool-installer@v1
      with:
        msvc-version: '2019'
        components: 'build-tools'

    - name: Build project
      run: msbuild /p:Configuration=Release 

    - name: Run executable
      run: .\x64\release\cpp-pass-params.exe
