name: C++ 2019 vs build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_run:
    runs-on: windows-2019

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: Enter VS Cmd terminal
      run: |
        call "c:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\Tools\VsDevCmd.bat"
        echo "Visual Studio Cmd prompt" 
        cd
        msbuild
    
    - name: Build project
      run: msbuild /p:Configuration=Release 

    - name: Run executable
      run: .\x64\release\cpp-pass-params.exe
