name: C++ 2019 vs build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_run:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: Find Visual Studio installation path
      id: find_vs_path
      run: |
        Get-ChildItem -Path 'C:\Program Files (x86)\Microsoft Visual Studio' -Directory | Where-Object { $_.Name -match "2019" } | Select-Object -ExpandProperty FullName | Out-File vs_path.txt

    - name: Set up Visual Studio environment
      run: |
        $vs_path = Get-Content vs_path.txt
        cd $vs_path
        .\Enterprise\Common7\Tools\VsDevCmd.bat
        
    - name: Build project
      run: msbuild /p:Configuration=Release 

    - name: Run executable
      run: .\x64\release\cpp-pass-params.exe
